export { default as About } from "./About"
export { default as CallToAction } from "./CallToAction"
export { default as Features } from "./Features"
export { default as Hero } from "./Hero"
export { default as LayoutFooter } from "./LayoutFooter"
export { default as LayoutHeader } from "./LayoutHeader"
export { default as Testimonials } from "./Testimonials"
export { default as LanguageCurrencySelector } from "./LanguageCurrencySelector"
