version: "3.8"
name: thelisting
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis-jobs:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  redis-cache:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis-data:/data
  browserless:
    image: browserless/chrome:latest
    restart: always
    ports:
      - "8080:3000"
    environment:
      - MAX_CONCURRENCY=10
      - TOKEN=browserless-token
