import { test, expect } from "vitest"

import { generateGoogleFontsUrl } from "~/utils/font"

test("generateGoogleFontsUrl", () => {
  const font1 = {
    family: "Roboto",
    variants: [
      "100",
      "100italic",
      "300",
      "300italic",
      "regular",
      "italic",
      "500",
      "500italic",
      "700",
      "700italic",
      "900",
      "900italic",
    ],
  }
  const font2 = undefined
  const font3 = { family: "Yesteryear", variants: ["regular"] }

  const url = generateGoogleFontsUrl([font1, font2, font3])

  expect(url).to.equal(
    // This value was generated by the [Google Fonts](https://fonts.google.com/)
    // site, adding the Roboto and Yesteryear fonts with all variants available.
    "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Yesteryear&display=swap",
  )
})
