name: Upload sourcemaps to Sentry

on:
  push:
    branches:
      - main

jobs:
  upload-sourcemaps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
        shell: bash
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: npm
      - run: npm install
      - name: Build sourcemaps
        run: npm run build:remix -- --sourcemap
      - name: Create new release
        run: |
          npx sentry-cli releases new ${{ github.sha }}
          npx sentry-cli releases set-commits --auto ${{ github.sha }}
      - name: Upload server sourcemaps
        run:
          npx sentry-cli releases files ${{ github.sha }} upload-sourcemaps ./build
          --ignore node_modules
          --ignore public
      - name: Upload client sourcemaps
        run:
          npx sentry-cli releases files ${{ github.sha }} upload-sourcemaps ./public
          --dist "client"
      - name: Finalize release
        run: npx sentry-cli releases finalize ${{ github.sha }}
